// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const PLACEHOLDER_URL = "https://qhvrielzimyihnnbnajr.supabase.co";
const PLACEHOLDER_KEY = "public-anon-key-missing-env";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === "your-anon-key") {
  console.warn(
    "GridLoad: copy .env.example to .env and set VITE_SUPABASE_PUBLISHABLE_KEY. The site will still render without live data."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
//
// Never pass empty URL/key into createClient — that throws "supabaseUrl is required"
// and leaves localhost:8080 as a blank white page.

export const supabase = createClient<Database>(
  SUPABASE_URL || PLACEHOLDER_URL,
  SUPABASE_PUBLISHABLE_KEY || PLACEHOLDER_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
